---
- name: Copy iterm2 dynamic profile
  template:
    src: iterm_profiles.json.j2
    dest: "{{ cli_home }}/Library/ApplicationSupport/iTerm2/DynamicProfiles/iterm_profiles.json"
    mode: '0644'
    owner: "{{ cli_user }}"
  vars:
    working_directory: "{{ cli_home | regex_replace('/', '\/') }}"
