---
- name: Create DynamicProfiles directory
  file:
    path: "{{ cli_home }}/Library/Application\ Support/iTerm2/DynamicProfiles"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_iterm_profiles_dir

- name: Copy iterm2 dynamic profile
  template:
    src: iterm_profiles.json.j2
    dest: "{{ cli_iterm_profiles_dir.path }}/iterm_profiles.json"
    mode: "0644"
    owner: "{{ cli_user }}"
  vars:
    working_directory: "{{ cli_home | regex_replace('/', '\/') }}"

- name: Download Oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ cli_install_dir }}/install_zsh.sh"

- name: Install Oh-my-zsh
  command:
    argv:
      - sh
      - "{{ cli_install_dir }}/install_zsh.sh"
      - --unattended
    creates: "{{ cli_home }}/.oh-my-zsh"

- name: Create zsh custom directory
  file:
    path: "{{ cli_install_dir }}/custom"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_zsh_custom_dir_obj

- name: Set zsh custom directory path variable
  set_fact:
    cli_zsh_custom_dir: "{{ cli_zsh_custom_dir_obj.path }}"

- name: Create zsh custom plugins directory
  file:
    path: "{{ cli_zsh_custom_dir }}/plugins"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_zsh_plugins_dir_obj

- name: Set zsh custom directory path variable
  set_fact:
    cli_zsh_plugins_dir: "{{ cli_zsh_plugins_dir_obj.path }}"

- name: Install zsh autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ cli_zsh_plugins_dir }}/zsh-autosuggestions"

- name: Install zsh syntax highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ cli_zsh_plugins_dir }}/zsh-syntax-highlighting"

- name: Install iTerm2 integration for zsh
  get_url:
    url: https://iterm2.com/shell_integration/zsh
    dest: "{{ cli_install_dir }}/.iterm2_zsh_integration"
