---
- name: Copy iterm2 dynamic profile
  template:
    src: iterm_profiles.json.j2
    dest: "{{ cli_home }}/Library/ApplicationSupport/iTerm2/DynamicProfiles/iterm_profiles.json"
    mode: '0644'
    owner: "{{ cli_user }}"
  vars:
    working_directory: "{{ cli_home | regex_replace('/', '\/') }}"

- name: Get path to fish
  command:
    argv:
      - which
      - fish
  register: cli_which_fish
  changed_when: False

- name: Get current user shell
  shell: "set -o pipefail && dscl . -read ~ UserShell | sed 's/UserShell: //'"
  register: cli_current_shell
  changed_when: False

- name: Append fish path to /etc/shells
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ cli_which_fish.stdout }}"
  when: cli_which_fish.rc == 0

- name: Change current user shell to fish
  become: yes
  become_method: sudo
  command:
    argv:
      - chsh
      - -s
      - "{{ cli_which_fish.stdout }}"
      - "{{ cli_user }}"
  when: cli_current_shell. rc == 0 and
        cli_which_fish.rc == 0 and
        cli_current_shell.stdout != cli_which_fish.stdout



  # vars:
  #   fish_path: "{{ cli_home }}/.local/share/omf"
  #   fish_config: "{{ cli_home }}/.config/omf"
