---
- name: Create DynamicProfiles directory
  file:
    path: "{{ cli_home }}/Library/Application\ Support/iTerm2/DynamicProfiles"
    state: directory
    mode: '0700'
    owner: "{{ cli_user }}"
  register: cli_iterm_profiles_dir

- name: Copy iterm2 dynamic profile
  template:
    src: iterm_profiles.json.j2
    dest: "{{ cli_iterm_profiles_dir.path }}/iterm_profiles.json"
    mode: '0700'
    owner: "{{ cli_user }}"
  vars:
    working_directory: "{{ cli_home | regex_replace('/', '\/') }}"

- name: Get path to fish
  command:
    argv:
      - which
      - fish
  register: cli_which_fish
  changed_when: False

- name: Get current user shell
  shell: "set -o pipefail && dscl . -read {{ cli_home | quote }} UserShell | sed 's/UserShell: //'"
  register: cli_current_shell
  changed_when: False

- name: Append fish path to /etc/shells
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ cli_which_fish.stdout }}"
  when: cli_which_fish.rc == 0

- name: Change current user shell to fish
  become: yes
  become_method: sudo
  command:
    argv:
      - chsh
      - -s
      - "{{ cli_which_fish.stdout }}"
      - "{{ cli_user }}"
  when: cli_current_shell. rc == 0 and
        cli_which_fish.rc == 0 and
        cli_current_shell.stdout != cli_which_fish.stdout

- name: Download Oh-my-fish
  get_url:
    url: https://get.oh-my.fish
    dest: "{{ cli_install_dir }}/install.omf"

- name: Install Oh-my-fish
  command:
    argv:
      - fish
      - "{{ cli_install_dir }}/install.omf"
      - --noninteractive
      - "--path={{ cli_install_dir }}/.local/share/omf"
      - "--config={{ cli_install_dir }}/.config/omf"
    creates: "{{ cli_install_dir }}/.local/share/omf/*"

- name: Install iTerm2 integration for fish
  get_url:
    url: https://iterm2.com/shell_integration/fish
    dest: "{{ cli_install_dir }}/.iterm2_shell_integration.fish"

- name: Copy Oh-my-fish configuration
  copy:
    src: omf
    dest: "{{ cli_install_dir }}/.config"
    mode: '0644'
    owner: "{{ cli_user }}"

- name: Install fish.init with iTerm2 integration support
  template:
    src: init.fish.j2
    dest: "{{ cli_install_dir }}/.config/omf/init.fish"
    mode: '0644'
    owner: "{{ cli_user }}"

  # vars:
  #   fish_path: "{{ cli_home }}/.local/share/omf"
  #   fish_config: "{{ cli_home }}/.config/omf"
