---
- name: Copy Brewfile
  copy:
    src: Brewfile
    dest: "{{ cli_install_dir }}/Brewfile"
    mode: '0644'
    owner: "{{ cli_user }}"

- name: Apply Brewfile
  command:
    argv:
      - /usr/local/bin/brew
      - bundle
      - install
      - -q
      - --cleanup
      - --force
      - --file
      - "{{ cli_install_dir }}/Brewfile"
    removes: "{{ cli_install_dir }}/Brewfile"
