---
- name: Copy Brewfile
  copy:
    src: Brewfile
    dest: "{{ cli_install_dir }}/Brewfile"
    mode: "0644"
    owner: "{{ cli_user }}"

- name: Apply Brewfile
  command:
    argv:
      - /usr/local/bin/brew
      - bundle
      - install
      - -q
      - --cleanup
      - --force
      - --file
      - "{{ cli_install_dir }}/Brewfile"
    removes: "{{ cli_install_dir }}/Brewfile"

- name: Install VSCode extension
  command:
    argv:
      - /usr/local/bin/code
      - --install-extension
      - "{{ item }}"
    creates: "{{ cli_home }}/.vscode/extensions/{{ item }}-*"
  loop:
    - esbenp.prettier-vscode
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - redhat.vscode-yaml
    - rust-lang.rust
    - svelte.svelte-vscode
    - timonwong.shellcheck
    - zbr.vscode-ansible

- name: Install idea CLI start script
  copy:
    src: idea
    dest: /usr/local/bin/idea
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Install remove gone git branches script
  copy:
    src: git-remove-branches.sh
    dest: /usr/local/bin/git-remove-branches.sh
    mode: "0755"
    owner: "{{ cli_user }}"
