---
- name: Define brew path
  set_fact:
    cli_brew_path: /usr/local/bin/brew

- name: Install brew formulae
  command:
    argv:
      - "{{ cli_brew_path }}"
      - install
      - -q
      - --formulae
      - ansible
      - ansible-lint
      - git
      - jq
      - maven
      - maven-completion
      - nmap
      - ripgrep
      - tree
  changed_when: False

- name: Tap the fonts casks
  command:
    argv:
      - "{{ cli_brew_path }}"
      - tap
      - homebrew/cask-fonts
  changed_when: False

- name: Install brew casks
  command:
    argv:
      - "{{ cli_brew_path }}"
      - install
      - -q
      - --force
      - --casks
      - docker
      - font-hack-nerd-font
      - insomnia
      - intellij-idea
      - iterm2
      - mockoon
      - obsidian
      - vagrant
      - vagrant-manager
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code

- name: Download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ cli_install_dir }}/rustup-init"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Install rust toolchain
  command:
    argv:
      - "{{ cli_install_dir }}/rustup-init"
      - -q
      - -y
      - --no-modify-path
    creates: "{{ cli_home }}/.cargo/*"

- name: Install VSCode extension
  command:
    argv:
      - /usr/local/bin/code
      - --install-extension
      - "{{ item }}"
    creates: "{{ cli_home }}/.vscode/extensions/{{ item | lower }}-*"
  loop:
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - ms-python.python
    - redhat.ansible
    - rust-lang.rust
    - svelte.svelte-vscode
    - timonwong.shellcheck

- name: Install idea CLI start script
  copy:
    src: idea
    dest: "{{ cli_binary_dir }}/idea"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Install remove gone git branches script
  copy:
    src: git-remove-branches.sh
    dest: "{{ cli_binary_dir }}/git-rmb"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Get sdkman installer
  get_url:
    url: https://get.sdkman.io?rcupdate=false
    dest: "{{ cli_install_dir }}/.sdkman_install"

- name: Install sdkman
  command:
    argv:
      - bash
      - "{{ cli_install_dir }}/.sdkman_install"
    creates: "{{ cli_home }}/.sdkman"
