---
- name: Copy Brewfile
  copy:
    src: Brewfile
    dest: "{{ cli_home }}/.Brewfile"
    mode: '0644'
    owner: "{{ cli_user }}"

- name: Apply Brewfile
  command:
    argv:
      - brew
      - bundle
      - install
      - --file
      - "{{ cli_home }}/.Brewfile"
    removes: "{{ cli_home }}/.Brewfile"
    creates: /Applications/iTerm.app
