---
- name: Copy Brewfile
  copy:
    src: Brewfile
    dest: "{{ cli_install_dir }}/Brewfile"
    mode: "0644"
    owner: "{{ cli_user }}"

# - name: Apply Brewfile
#   command:
#     argv:
#       - "{{ cli_home }}/homebrew/bin/brew"
#       - bundle
#       - install
#       - -q
#       - --cleanup
#       - --force
#       - --file
#       - "{{ cli_install_dir }}/Brewfile"
#     removes: "{{ cli_install_dir }}/Brewfile"

- name: Download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ cli_install_dir }}/rustup-init"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Install rust toolchain
  command:
    argv:
      - "{{ cli_install_dir }}/rustup-init"
      - -q
      - -y
      - --no-modify-path
    creates: "{{ cli_home }}/.cargo/*"

- name: Install VSCode extension
  command:
    argv:
      - "{{ cli_binary_dir }}/bin/code"
      - --install-extension
      - "{{ item }}"
    creates: "{{ cli_home }}/.vscode/extensions/{{ item | lower }}-*"

  loop:
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - ms-python.python
    - redhat.ansible
    - rust-lang.rust
    - svelte.svelte-vscode
    - timonwong.shellcheck

- name: Install idea CLI start script
  copy:
    src: idea
    dest: "{{ cli_binary_dir }}/idea"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Install remove gone git branches script
  copy:
    src: git-remove-branches.sh
    dest: "{{ cli_binary_dir }}/git-remove-branches"
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Get sdkman installer
  get_url:
    url: https://get.sdkman.io?rcupdate=false
    dest: "{{ cli_install_dir }}/.sdkman_install"

- name: Install sdkman
  command:
    argv:
      - bash
      - "{{ cli_install_dir }}/.sdkman_install"
    creates: "{{ cli_home }}/.sdkman"
