---
- name: Copy Brewfile
  ansible.builtin.copy:
    src: Brewfile
    dest: "{{ cli_home }}/.Brewfile"
    mode: '0644'
    owner: "{{ cli_user }}"

- name: Apply Brewfile
  ansible.builtin.command:
    argv:
      - brew
      - bundle
      - install
      - --file
      - "{{ cli_home }}/.Brewfile"
    removes: "{{ cli_home }}/.Brewfile"
    creates: /Applications/iTerm.app

- name: Remove Brewfile
  ansible.builtin.file:
    path: "{{ cli_home }}/.Brewfile"
    state: absent
