---
- name: Create installation dotdir
  file:
    path: "{{ cli_home }}/.cli"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_dir

- name: Set installation directory variable
  set_fact:
    cli_install_dir: "{{ cli_dir.path }}"

- name: Create cli bin dotdir
  file:
    path: "{{ cli_install_dir }}/bin"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_bin_dir

- name: Set cli binary directory variable
  set_fact:
    cli_binary_dir: "{{ cli_bin_dir.path }}"

- name: Create private projects dir
  file:
    path: "{{ cli_home }}/Documents/Code/projects"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"

- name: Create work projects dir
  file:
    path: "{{ cli_home }}/Documents/Code/work"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_work_dir

- name: Set work projects directory variable
  set_fact:
    cli_work_projects_dir: "{{ cli_work_dir.path }}"

- name: Check whether command line tools are already installed
  command:
    argv:
      - xcode-select
      - -p
  ignore_errors: yes
  register: cli_tools_installed
  changed_when: False
  failed_when: cli_tools_installed.rc != 0 and cli_tools_installed.rc != 2

- name: Enable built-in git on MacOS
  command:
    argv:
      - xcode-select
      - --install
  when: cli_tools_installed.rc == 2
