---
- name: Copy Oh-my-fish configuration
  copy:
    src: omf
    dest: "{{ cli_install_dir }}/.config"
    mode: "0644"
    owner: "{{ cli_user }}"

- name: Install fish.init with iTerm2 integration support
  template:
    src: init.fish.j2
    dest: "{{ cli_install_dir }}/.config/omf/init.fish"
    mode: "0644"
    owner: "{{ cli_user }}"

- name: Install sdk for fish
  command:
    argv:
      - omf
      - install
      - sdk
    creates: "{{ cli_install_dir }}/.local/share/omf/pkg/sdk/*"

- name: Create VSCode user settings directory
  file:
    path: "{{ cli_home }}/Library/Application\ Support/Code/User"
    state: directory
    mode: "0755"
    owner: "{{ cli_user }}"
  register: cli_vscode_settings

- name: Set vscode user settings directory variable
  set_fact:
    cli_vscode_settings_dir: "{{ cli_vscode_settings.path }}"

- name: Copy VSCode user settings
  copy:
    src: vsc_user_settings.json
    dest: "{{ cli_vscode_settings_dir }}/settings.json"
    mode: "0644"
    owner: "{{ cli_user }}"

- name: Install global .gitconfig
  template:
    src: .gitconfig.j2
    dest: "{{ cli_home }}/.gitconfig"
    mode: "0644"
    owner: "{{ cli_user }}"

- name: Install work .gitconfig overrides
  template:
    src: .gitconfig_work.j2
    dest: "{{ cli_work_projects_dir }}/.gitconfig"
    mode: "0644"
    owner: "{{ cli_user }}"
